services:
  api:
    image: node:22
    command: bash -c "npm install && npm run start:dev"
    working_dir: /app
    volumes:
      - ./api/:/app
      - ./shared/:/app/src/shared
    ports:
      - ${PORT_API}:4000
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017
      DATABASE_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017
      MONGO_DB_NAME: ${DB_NAME}

  watcher:
    image: oven/bun:1.1
    command: bash -c " bun --watch run main.ts"
    working_dir: /app
    volumes:
      - ./watcher/:/app
    environment:
      NODE_ENV: ${NODE_ENV}

      MONGO_URI: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017
      MONGO_DB_NAME: ${DB_NAME}

      EVM_RPC: https://mainnet.infura.io/v3/${INFURA_IPFS_ID}

  ide:
    image: node:22
    command: bash -c "tail -f"
    # command: bash -c "npm install && npm run dev"
    # command: bash -c "npm install && npm run dev -- --host 0.0.0.0 --port 3999"
    working_dir: /app
    volumes:
      - ./web/ide/:/app
    ports:
      # - ${PORT_WEB1_APP}:3000
      - ${PORT_IDE_APP}:3999
    environment:
      NODE_ENV: ${NODE_ENV}

  market:
    image: node:22
    command: bash -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./web/market/:/app
    ports:
      - ${PORT_MARKET_APP}:3000
    environment:
      NODE_ENV: ${NODE_ENV}

  mongo:
    image: mongo:8.0
    volumes:
      - ./storage/dbs/mongo:/data/db/
    ports:
      - ${PORT_DB}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}